FROM node:21.1.0-alpine3.18 as reactUI
WORKDIR /app
COPY ./package.json ./
RUN npm install --force --loglevel verbose
COPY . .
RUN npm run build

# Agregar este comando para verificar el contenido del directorio
RUN ls -la /app/dist

FROM nginx:latest
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=reactUI /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
