version: '3.8'

# Services
services:
  # Server service
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.node
    container_name: backend
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

  # Client service
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.reactUI
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - server

  # Database service
  mongodb:
    image: mongo:latest
    container_name: talentin-mongo
    ports:
      - "27017:27017"

    volumes:
      - ./../mydata:/data/db

# Volumes define
volumes: 
  mydata: